version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"  # 외부 포트 8080으로 매핑
    environment:
      - NODE_ENV=production
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT:-3306}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-24h}
      - PORT=3000
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 